"""Split shipping address into name phone address

Revision ID: 445cc141ea2c
Revises: 
Create Date: 2026-07-07 11:39:33.778377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445cc141ea2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.Text(), nullable=True))
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('customer_address')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
